# Generated by Django 3.2.6 on 2021-08-24 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210824_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={},
        ),
        migrations.RemoveField(
            model_name='books',
            name='content',
        ),
        migrations.RemoveField(
            model_name='books',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='books',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='books',
            name='status',
        ),
        migrations.RemoveField(
            model_name='books',
            name='updated_on',
        ),
    ]
